### ISSUE TITLE
Can't install with Laravel Framework 9.2

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mll-lab/laravel-graphql-voyager#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mll-lab/laravel-graphql-voyager v1.0.2 -> satisfiable by mll-lab/laravel-graphql-voyager[v1.0.2].
    - mll-lab/laravel-graphql-voyager v1.0.2 requires illuminate/console 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 || ^8 -> found illuminate/console[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ...,
 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by LiamKarlMitchell** [comment]
Made a fork and edited it till it worked, not sure on the exact versions to put in composer.json however.
https://github.com/LiamKarlMitchell/laravel-graphql-voyager/blob/master/composer.json

Saw another fork after posting this which has also made changes.
https://github.com/jorisneuteboom/laravel-graphql-voyager/blob/master/composer.json

Happy to do a pull request if you think its okay.

To load it in my project temporarily until its fixed here I put this in my projects composer.json
```
    "repositories": {
        "laravel-graphql-voyager": {
            "type": "vcs",
            "url": "https://github.com/liamkarlmitchell/laravel-graphql-voyager"
        }
```

Then I ran
```
sail composer require mll-lab/laravel-graphql-voyager:master
```

**Comment by spawnia** [comment]
Fixed with https://github.com/mll-lab/laravel-graphql-voyager/releases/tag/v2.0.0
