### ISSUE TITLE
Keep receiving CSRF mismatch error

### ISSUE THREAD

**Issue by digitdash** [mll-lab/laravel-graphql-voyager#7]
<img width="666" alt="Screenshot 2023-08-06 at 11 45 39 AM" src="https://github.com/mll-lab/laravel-graphql-voyager/assets/128324459/c02d756e-002b-4bdc-890a-3b34bd7cf80f">

It seems to work locally, but when I try remotely it always returns this error.

**Comment by spawnia** [comment]
Please try if https://github.com/mll-lab/laravel-graphiql#configure-session-authentication applies here as well.

**Comment by spawnia** [comment]
Closing due to lack of feedback.
